//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _9M.Work.WPF_Main.UpdateGoodsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://my.9mg.cc/", ConfigurationName="UpdateGoodsServiceReference.GetGoodsServerSoap")]
    public interface GetGoodsServerSoap {
        
        // CODEGEN: 命名空间 http://my.9mg.cc/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://my.9mg.cc/HelloWorld", ReplyAction="*")]
        _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponse HelloWorld(_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://my.9mg.cc/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponse> HelloWorldAsync(_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://my.9mg.cc/ 的元素名称 requestkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://my.9mg.cc/GetGoodsPrice", ReplyAction="*")]
        _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponse GetGoodsPrice(_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://my.9mg.cc/GetGoodsPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponse> GetGoodsPriceAsync(_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest request);
        
        // CODEGEN: 命名空间 http://my.9mg.cc/ 的元素名称 requestkey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://my.9mg.cc/UpDatePrice", ReplyAction="*")]
        _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponse UpDatePrice(_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://my.9mg.cc/UpDatePrice", ReplyAction="*")]
        System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponse> UpDatePriceAsync(_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://my.9mg.cc/", Order=0)]
        public _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://my.9mg.cc/", Order=0)]
        public _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://my.9mg.cc/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsPrice", Namespace="http://my.9mg.cc/", Order=0)]
        public _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequestBody Body;
        
        public GetGoodsPriceRequest() {
        }
        
        public GetGoodsPriceRequest(_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://my.9mg.cc/")]
    public partial class GetGoodsPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string goodsno;
        
        public GetGoodsPriceRequestBody() {
        }
        
        public GetGoodsPriceRequestBody(string requestkey, string goodsno) {
            this.requestkey = requestkey;
            this.goodsno = goodsno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsPriceResponse", Namespace="http://my.9mg.cc/", Order=0)]
        public _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponseBody Body;
        
        public GetGoodsPriceResponse() {
        }
        
        public GetGoodsPriceResponse(_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://my.9mg.cc/")]
    public partial class GetGoodsPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsPriceResult;
        
        public GetGoodsPriceResponseBody() {
        }
        
        public GetGoodsPriceResponseBody(string GetGoodsPriceResult) {
            this.GetGoodsPriceResult = GetGoodsPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpDatePriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpDatePrice", Namespace="http://my.9mg.cc/", Order=0)]
        public _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequestBody Body;
        
        public UpDatePriceRequest() {
        }
        
        public UpDatePriceRequest(_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://my.9mg.cc/")]
    public partial class UpDatePriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string JsonStr;
        
        public UpDatePriceRequestBody() {
        }
        
        public UpDatePriceRequestBody(string requestkey, string JsonStr) {
            this.requestkey = requestkey;
            this.JsonStr = JsonStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpDatePriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpDatePriceResponse", Namespace="http://my.9mg.cc/", Order=0)]
        public _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponseBody Body;
        
        public UpDatePriceResponse() {
        }
        
        public UpDatePriceResponse(_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://my.9mg.cc/")]
    public partial class UpDatePriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpDatePriceResult;
        
        public UpDatePriceResponseBody() {
        }
        
        public UpDatePriceResponseBody(string UpDatePriceResult) {
            this.UpDatePriceResult = UpDatePriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetGoodsServerSoapChannel : _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGoodsServerSoapClient : System.ServiceModel.ClientBase<_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap>, _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap {
        
        public GetGoodsServerSoapClient() {
        }
        
        public GetGoodsServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetGoodsServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetGoodsServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetGoodsServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponse _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap.HelloWorld(_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest inValue = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest();
            inValue.Body = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequestBody();
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponse retVal = ((_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponse> _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap.HelloWorldAsync(_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldResponse> HelloWorldAsync() {
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest inValue = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequest();
            inValue.Body = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.HelloWorldRequestBody();
            return ((_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponse _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap.GetGoodsPrice(_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest request) {
            return base.Channel.GetGoodsPrice(request);
        }
        
        public string GetGoodsPrice(string requestkey, string goodsno) {
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest inValue = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest();
            inValue.Body = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequestBody();
            inValue.Body.requestkey = requestkey;
            inValue.Body.goodsno = goodsno;
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponse retVal = ((_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap)(this)).GetGoodsPrice(inValue);
            return retVal.Body.GetGoodsPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponse> _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap.GetGoodsPriceAsync(_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest request) {
            return base.Channel.GetGoodsPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceResponse> GetGoodsPriceAsync(string requestkey, string goodsno) {
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest inValue = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequest();
            inValue.Body = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsPriceRequestBody();
            inValue.Body.requestkey = requestkey;
            inValue.Body.goodsno = goodsno;
            return ((_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap)(this)).GetGoodsPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponse _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap.UpDatePrice(_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest request) {
            return base.Channel.UpDatePrice(request);
        }
        
        public string UpDatePrice(string requestkey, string JsonStr) {
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest inValue = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest();
            inValue.Body = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequestBody();
            inValue.Body.requestkey = requestkey;
            inValue.Body.JsonStr = JsonStr;
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponse retVal = ((_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap)(this)).UpDatePrice(inValue);
            return retVal.Body.UpDatePriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponse> _9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap.UpDatePriceAsync(_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest request) {
            return base.Channel.UpDatePriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<_9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceResponse> UpDatePriceAsync(string requestkey, string JsonStr) {
            _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest inValue = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequest();
            inValue.Body = new _9M.Work.WPF_Main.UpdateGoodsServiceReference.UpDatePriceRequestBody();
            inValue.Body.requestkey = requestkey;
            inValue.Body.JsonStr = JsonStr;
            return ((_9M.Work.WPF_Main.UpdateGoodsServiceReference.GetGoodsServerSoap)(this)).UpDatePriceAsync(inValue);
        }
    }
}
